### PR TITLE
Loading example

### PR DESCRIPTION
**Pull request by rogermc2**
Example demonstrating the loading of vertices data from an `OBJ` file.

### CODE REVIEW

**Comment by rogermc2** [comment]
I've decided to combine the DDS and OBJ loader files.
Please delay processing this PR until complete.

**Comment by flyx** [comment]
Sorry for not being very responsive. There are commits from a few days ago, are you still working on this?

**Comment by rogermc2** [comment]
No I've completed this.
I've been adding stuff needed for other projects.
If you are readt to merge please do so, I'll refrain from further commits.

**Comment by rogermc2** [comment]
Great!

**Pull request merged**
