### PR TITLE
New examples

### PR DESCRIPTION
**Pull request by rogermc2**

### CODE REVIEW

**Comment by rogermc2** [comment]
I'm a bit baffled.
Git seems to put the code for this request into a new directory ?

**Comment by flyx** [comment]
Well one directory is named `example` while the other is named `Example`. Mind the casing.

**Comment by rogermc2** [comment]
Yes. That's what I noticed.
But I don't know where the E came from.
My directory structure here is
OpenGLAda
   examples
      Moving_Triangle
      Simplest

Its as if GitHub Desktop changed examples to Examples.
So, at the moment, I can't figure out what to do.
Looking at History in GitHub Desktop, the directories are definitely shown as
examples/Superbible/Moving_Triangle/src/

So, where did the capital E come from?

**Comment by rogermc2** [comment]
I deleted this and opened a new one, #29 then committed and pushed my Moving_Triangles files.
But I still see an Examples and an examples directory.
Should I change the name of my examples directory to Examples?

**Comment by rogermc2** [comment]
OK. Confusion on my part yet again
Somehow, I got the titles mixed up. I've now changed my local directory name to Examples.

**Pull request closed without merging**
