### PR TITLE
Textured cube example using Stream_IO

### PR DESCRIPTION
**Pull request by rogermc2**

### CODE REVIEW

**Comment by rogermc2** [comment]
Using Stream_IO and other changes has provided a vast improvement over the original C code.

**Comment by rogermc2** [comment]
I notice that this PR hasn't been accepted yet.
Is there anything else that I need to fix?
I won't be doing more of these tutorials for a while as I now have enough experience, I hope, to pursue my main field of interest, Geometric Algebra.
My interest in OpenGL arose from the book, Geometric Algebra for Computer Science, which uses OpenGL extensively in its text, examples and exercises.
If you think it may be of use, I could introduce a Geometric Algebra directory to Examples.

**Comment by flyx** [comment]
I will check it next week. I was busy moving houses the last two weeks so I didn't have any time for this PR. Today I am hopefully finishing moving my stuff. Also, I was traveling to Berlin last weekend to discuss the future of YAML with some people. To sum up: My response times will get better next week ;).

**Comment by rogermc2** [comment]
That's fine. I trust that the house moving went well.

**Pull request merged**
